name: Mule CI / CD

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

env:
  ANYPOINT_CONNECTED_APP_CLIENT_ID: ${{ secrets.ANYPOINT_CONNECTED_APP_CLIENT_ID }}
  ANYPOINT_CONNECTED_APP_CLIENT_SECRET: ${{ secrets.ANYPOINT_CONNECTED_APP_CLIENT_SECRET }}

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -B

      - name: Archive build artifact
        uses: actions/upload-artifact@v3
        with:
          name: mule-app
          path: target/*.jar  

  publish-and-deploy:
    name: Publish to Exchange & Deploy to CloudHub
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download built artifact
        uses: actions/download-artifact@v3
        with:
          name: mule-app
          path: target/

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Verify Maven settings.xml exists
        run: |
          if [ ! -f "./settings.xml" ]; then
            echo "❌ settings.xml not found. Make sure it's in the repo root."
            exit 1
          fi

      - name: Deploy to Exchange (publish)
        run: mvn deploy -B -Dmaven.test.skip=true --settings ./settings.xml

      - name: Deploy to CloudHub
        run: mvn clean deploy -B -DmuleDeploy --settings ./settings.xml
