name: Mule CI / CD

on:
  push:
    branches:
      - master   # or whichever branch you deploy from
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -B

      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-app
          path: target/*.jar  # adjust if your artifact name is different

  publish-and-deploy:
    name: Publish to Exchange & Deploy to CloudHub
    runs-on: ubuntu-latest
    needs: build

    # 👇 Inject the credentials as JVM options so Maven can resolve ${env.VAR}
    env:
      MAVEN_OPTS: >
        -Denv.ANYPOINT_CONNECTED_APP_CLIENT_ID=${{ secrets.ANYPOINT_CONNECTED_APP_CLIENT_ID }}
        -Denv.ANYPOINT_CONNECTED_APP_CLIENT_SECRET=${{ secrets.ANYPOINT_CONNECTED_APP_CLIENT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: mule-app
          path: target/

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cp ./settings.xml ~/.m2/settings.xml

      - name: Debug Maven env vars (optional — remove after testing)
        run: |
          echo "Client ID: ${ANYPOINT_CONNECTED_APP_CLIENT_ID}"
          echo "Client Secret length: ${#ANYPOINT_CONNECTED_APP_CLIENT_SECRET}"

      - name: Deploy to Exchange (publish)
        run: mvn deploy -B -Dmaven.test.skip=true --settings ~/.m2/settings.xml

      - name: Deploy to CloudHub
        run: mvn clean deploy -B -DmuleDeploy --settings ~/.m2/settings.xml
